In [1]:
# Import pandas
# Used to work with DataFrames and CSV files
import pandas as pd

In [ ]:
# DataFrame() - Create DataFrame from dictionary
data = {"Name": ["A", "B", "C", "D"], "Age": [20, 30, 40, 50]}
df = pd.DataFrame(data)
df

In [2]:
# DataFrame() - Create DataFrame from list of dictionaries
df = pd.DataFrame([
    {"Name": "Akshay", "Age": 24},
    {"Name": "Ajay", "Age": 23},
    {"Name": "Jay", "Age": 35},
])
df

     Name  Age
0  Akshay   24
1    Ajay   23
2     Jay   35

In [8]:
# read_csv() - Load data from CSV file
df = pd.read_csv("data.csv")
df.head()

     Name  Age
0  Akshay   24
1    Ajay   23
2     Jay   35
3   Akash   26
4   Vikas   33

In [7]:
# info() - Display dataset structure and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     7 non-null      int64
dtypes: int64(1), object(1)
memory usage: 244.0+ bytes

In [ ]:
# head() - Show top 2 rows
df.head(2)

     Name  Age
0  Akshay   24
1    Ajay   23

In [ ]:
# tail() - Show bottom 2 rows
df.tail(2)

      Name  Age
5  Hemanth   26
6    Pavan   25

In [12]:
# Column Selection - Access specific column
df = pd.read_csv("weather.csv")
df["city"]

0    Bengaluru
1     Tumakuru
2      Raichur
3        Udupi
Name: city, dtype: object

In [14]:
# loc - Select row by label
df.loc[2]

city           Raichur
temp              37.5
humidity            53
rain(in mm)         10
Name: 2, dtype: object

In [16]:
# iloc - Select rows by index
# Same as that of slicing, start is inclusive, end is exclusive
df.iloc[0:3]

        city  temp  humidity  rain(in mm)
0  Bengaluru  35.3        45           12
1   Tumakuru  32.6        34           26
2    Raichur  37.5        53           10

In [17]:
# Conditional Filtering - Filter rows based on condition
df[df["temp"] > 35.5]

      city  temp  humidity  rain(in mm)
2  Raichur  37.5        53           10
3    Udupi  36.3        58           34

In [18]:
# Multiple Conditions - Apply AND condition
df[(df["humidity"] > 40) & (df["humidity"] < 50)]

        city  temp  humidity  rain(in mm)
0  Bengaluru  35.3        45           12

In [19]:
# Update Column - Modify column values
df["humidity"] = df["humidity"] + 1
df

        city  temp  humidity  rain(in mm)
0  Bengaluru  35.3        46           12
1   Tumakuru  32.6        35           26
2    Raichur  37.5        54           10
3      Udupi  36.3        59           34

In [21]:
# isnull() - Check missing values
df = pd.read_csv("weather.csv")
df.isnull()

    city   temp  humidity  rain(in mm)
0  False  False     False        False
1  False  False     False        False
2  False  False     False        False
3  False  False     False        False
4  False   True     False        False
5  False  False      True        False

In [22]:
# fillna() - Replace missing values
df.fillna(0, inplace=True)
df

            city  temp  humidity  rain(in mm)
0      Bengaluru  35.3      45.0           12
1       Tumakuru  32.6      34.0           26
2        Raichur  37.5      53.0           10
3          Udupi  36.3      58.0           34
4  Chikkamagluru   0.0      25.0           32
5         Kodagu  36.5       0.0           30

In [23]:
# describe() - Statistical summary of data
df.describe()

            temp   humidity  rain(in mm)
count   6.000000   6.000000     6.000000
mean   29.700000  35.833333    24.000000
std    14.645819  21.329948    10.430724
min     0.000000   0.000000    10.000000
25%    33.275000  27.250000    15.500000
50%    35.800000  39.500000    28.000000
75%    36.450000  51.000000    31.500000
max    37.500000  58.000000    34.000000

In [24]:
# mean() - Calculate average of column
df["humidity"].mean()

np.float64(35.833333333333336)

In [25]:
# sum() - Calculate total of column
df["humidity"].sum()

np.float64(215.0)

In [28]:
df.sort_values("temp")

            city  temp  humidity  rain(in mm)
4  Chikkamagluru   0.0      25.0           32
1       Tumakuru  32.6      34.0           26
0      Bengaluru  35.3      45.0           12
3          Udupi  36.3      58.0           34
5         Kodagu  36.5       0.0           30
2        Raichur  37.5      53.0           10

In [ ]:
# sort_values() - Sort data by column
df.sort_values("city")

            city  temp  humidity  rain(in mm)
4  Chikkamagluru   0.0      25.0           32
1       Tumakuru  32.6      34.0           26
0      Bengaluru  35.3      45.0           12
3          Udupi  36.3      58.0           34
5         Kodagu  36.5       0.0           30
2        Raichur  37.5      53.0           10

In [29]:
# groupby() - Group data and aggregate
data = {
    "Dept": ["Dev", "Dev", "QA", "Dev", "QA"],
    "Salary": [15000, 18000, 13000, 20000, 16000]
}
df = pd.DataFrame(data)
df.groupby("Dept").sum()

      Salary
Dept
Dev    53000
QA     29000

In [30]:
# unique() - Get unique values
df["Dept"].unique()

array(['Dev', 'QA'], dtype=object)

In [31]:
# value_counts() - Count occurrences
df["Dept"].value_counts()

Dept
Dev    3
QA     2
Name: count, dtype: int64

In [33]:
# to_csv() - Export DataFrame to CSV
df.to_csv("dept.csv", index=False)